version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "${PG_HOST_PORT:-5432}:5432"
    volumes:
      - friendlystripe-local-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: friendlystripe
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

volumes:
  friendlystripe-local-postgres:
