// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_tax_ids.sql

package postgres

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const deleteAllCustomerTaxIDs = `-- name: DeleteAllCustomerTaxIDs :exec
DELETE FROM "stripe"."customer_tax_ids"
`

func (q *Queries) DeleteAllCustomerTaxIDs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllCustomerTaxIDs)
	return err
}

const deleteCustomerTaxID = `-- name: DeleteCustomerTaxID :exec
DELETE FROM "stripe"."customer_tax_ids" WHERE id = $1
`

func (q *Queries) DeleteCustomerTaxID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerTaxID, id)
	return err
}

const deleteCustomerTaxIDsOfCustomer = `-- name: DeleteCustomerTaxIDsOfCustomer :exec
DELETE FROM "stripe"."customer_tax_ids" WHERE customer = $1
`

func (q *Queries) DeleteCustomerTaxIDsOfCustomer(ctx context.Context, customer string) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerTaxIDsOfCustomer, customer)
	return err
}

const deleteCustomerTaxIDsOfCustomerExcept = `-- name: DeleteCustomerTaxIDsOfCustomerExcept :exec
DELETE FROM "stripe"."customer_tax_ids" WHERE customer = $1 AND id <> ALL($2::text[])
`

type DeleteCustomerTaxIDsOfCustomerExceptParams struct {
	Customer string
	KeepIds  []string
}

func (q *Queries) DeleteCustomerTaxIDsOfCustomerExcept(ctx context.Context, arg DeleteCustomerTaxIDsOfCustomerExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerTaxIDsOfCustomerExcept, arg.Customer, pq.Array(arg.KeepIds))
	return err
}

const upsertCustomerTaxID = `-- name: UpsertCustomerTaxID :exec
INSERT INTO "stripe"."customer_tax_ids" (
    id, object, country, created, livemode, type, value, verification, customer, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW()
) ON CONFLICT (id) DO UPDATE SET 
    object = EXCLUDED.object,
    country = EXCLUDED.country,
    created = EXCLUDED.created,
    livemode = EXCLUDED.livemode,
    type = EXCLUDED.type,
    value = EXCLUDED.value,
    verification = EXCLUDED.verification,
    customer = EXCLUDED.customer,
    updated_at = NOW()
`

type UpsertCustomerTaxIDParams struct {
	ID           string
	Object       string
	Country      sql.NullString
	Created      int64
	Livemode     bool
	Type         string
	Value        string
	Verification pqtype.NullRawMessage
	Customer     string
}

func (q *Queries) UpsertCustomerTaxID(ctx context.Context, arg UpsertCustomerTaxIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertCustomerTaxID,
		arg.ID,
		arg.Object,
		arg.Country,
		arg.Created,
		arg.Livemode,
		arg.Type,
		arg.Value,
		arg.Verification,
		arg.Customer,
	)
	return err
}
