// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgres

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type StripeCoupon struct {
	ID               string
	Object           string
	AmountOff        sql.NullInt64
	Created          int64
	Currency         sql.NullString
	Duration         string
	DurationInMonths sql.NullInt64
	Livemode         bool
	MaxRedemptions   sql.NullInt64
	Metadata         pqtype.NullRawMessage
	Name             string
	PercentOff       sql.NullFloat64
	RedeemBy         sql.NullInt64
	TimesRedeemed    sql.NullInt64
	Valid            bool
	AppliesTo        pqtype.NullRawMessage
	UpdatedAt        time.Time
}

type StripeCustomer struct {
	ID                  string
	Object              string
	Address             pqtype.NullRawMessage
	Description         sql.NullString
	Email               sql.NullString
	Metadata            pqtype.NullRawMessage
	Name                sql.NullString
	Phone               sql.NullString
	Shipping            pqtype.NullRawMessage
	Balance             sql.NullInt64
	Created             int64
	Currency            sql.NullString
	DefaultSource       sql.NullString
	Delinquent          bool
	Discount            pqtype.NullRawMessage
	InvoicePrefix       string
	InvoiceSettings     pqtype.NullRawMessage
	Livemode            bool
	NextInvoiceSequence int64
	PreferredLocales    []string
	TaxExempt           string
	Deleted             bool
	UpdatedAt           time.Time
}

type StripePrice struct {
	ID                string
	Object            string
	Active            bool
	Currency          string
	Metadata          pqtype.NullRawMessage
	Nickname          sql.NullString
	Recurring         pqtype.NullRawMessage
	Type              string
	UnitAmount        sql.NullInt64
	BillingScheme     string
	Created           int64
	Livemode          bool
	LookupKey         sql.NullString
	TiersMode         sql.NullString
	TransformQuantity pqtype.NullRawMessage
	UnitAmountDecimal sql.NullFloat64
	Product           string
	UpdatedAt         time.Time
}

type StripeProduct struct {
	ID                  string
	Object              string
	Active              bool
	Description         sql.NullString
	Metadata            pqtype.NullRawMessage
	Name                string
	Created             int64
	Images              []string
	Livemode            bool
	PackageDimensions   pqtype.NullRawMessage
	Shippable           bool
	StatementDescriptor sql.NullString
	UnitLabel           sql.NullString
	Updated             int64
	Url                 sql.NullString
	UpdatedAt           time.Time
}

type StripeSubscription struct {
	ID                            string
	Object                        string
	CancelAtPeriodEnd             bool
	CurrentPeriodEnd              int64
	CurrentPeriodStart            int64
	DefaultPaymentMethod          sql.NullString
	Metadata                      pqtype.NullRawMessage
	PendingSetupIntent            sql.NullString
	PendingUpdate                 pqtype.NullRawMessage
	Status                        string
	ApplicationFeePercent         sql.NullFloat64
	BillingCycleAnchor            int64
	BillingThresholds             pqtype.NullRawMessage
	CancelAt                      sql.NullInt64
	CanceledAt                    sql.NullInt64
	CollectionMethod              string
	Created                       int64
	DaysUntilDue                  sql.NullInt64
	DefaultSource                 sql.NullString
	DefaultTaxRates               pqtype.NullRawMessage
	EndedAt                       sql.NullInt64
	Livemode                      bool
	NextPendingInvoiceItemInvoice sql.NullInt64
	PauseCollection               pqtype.NullRawMessage
	PendingInvoiceItemInterval    pqtype.NullRawMessage
	StartDate                     int64
	TransferData                  pqtype.NullRawMessage
	TrialEnd                      sql.NullInt64
	TrialStart                    sql.NullInt64
	DiscountID                    sql.NullString
	DiscountStart                 sql.NullInt64
	DiscountEnd                   sql.NullInt64
	DiscountCoupon                sql.NullString
	DiscountDeleted               sql.NullBool
	DiscountPromotionCode         sql.NullString
	Schedule                      sql.NullString
	Customer                      string
	UpdatedAt                     time.Time
}

type StripeSubscriptionItem struct {
	ID                string
	Object            string
	BillingThresholds pqtype.NullRawMessage
	Created           int64
	Metadata          pqtype.NullRawMessage
	Quantity          int64
	Price             string
	Subscription      string
	TaxRates          pqtype.NullRawMessage
}

type StripeSyncState struct {
	ID        string
	LastEvent int64
}
